# Important information: https://intuit.github.io/auto/docs/build-platforms/github-actions

name: Release on NPM

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository under ./libMvrGdtf
        uses: actions/checkout@v4
        with:
          path: libMvrGdtf
          fetch-depth: 0
          fetch-tags: true
          token: ${{ secrets.ADMIN_TOKEN }}

      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://npm.pkg.github.com/
          scope: '@mvrdevelopment'

      - name: Build
        uses: ./libMvrGdtf/.github/actions/build-lib

      - name: Create Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        working-directory: libMvrGdtf
        run: |
          npm install
          git config user.email "auto-release-bot@mvrdevelopment.com"
          git config user.name "Auto release bot"
          npm run release
